### ISSUE TITLE
doesn't work unless markdown-it-attrs is set to {}

### ISSUE THREAD

**Issue by nonchip** [mb21/markdown-it-bracketed-spans#1]
because https://github.com/mb21/markdown-it-bracketed-spans/blob/cb48bc02eb5e0ad307aec5191f8d97458d129efd/index.js#L22

**Comment by mb21** [comment]
From the README:

> Must be used together with the markdown-it-attrs plugin

Are you doing that?

**Comment by nonchip** [comment]
yes, as i said in the title. `markdown-it-attrs` allows for custom delimiters though (via `leftDelimiter` and `rightDelimiter` in the 2nd argument object to `markdownIt().use(attrs,{...})`), and you're hardcoding `{}`. oh also if i fix that manually (either by making attrs use the default ones or by copying your code and modifying that line), i get:

```
> Cannot read property 'attrJoin' of undefined (TypeError):
    TypeError: Cannot read property 'attrJoin' of undefined
        at Object.exports.addAttrs (/home/kyra/Documents/PnP/TheElpisSystem/node_modules/markdown-it-attrs/utils.js:123:13)
        at Object.transform (/home/kyra/Documents/PnP/TheElpisSystem/node_modules/markdown-it-attrs/patterns.js:131:15)
        at Array.curlyAttrs (/home/kyra/Documents/PnP/TheElpisSystem/node_modules/markdown-it-attrs/index.js:30:19)
        at Core.process (/home/kyra/Documents/PnP/TheElpisSystem/node_modules/markdown-it/lib/parser_core.js:51:13)
        at MarkdownIt.parse (/home/kyra/Documents/PnP/TheElpisSystem/node_modules/markdown-it/lib/index.js:523:13)
        at MarkdownIt.render (/home/kyra/Documents/PnP/TheElpisSystem/node_modules/markdown-it/lib/index.js:543:36)
        at /home/kyra/Documents/PnP/TheElpisSystem/node_modules/@11ty/eleventy/src/Engines/Markdown.js:66:38
```

the markdown source for that error is:
```markdown
GMs: [if you want to allow your group to start with a ship, the sum of all bonuses and health values should be `10 + 2*(number of characters)`]{.spoiler}
```

seems like it's unable to find the span's attributes object to write to?

**Comment by mb21** [comment]
Yes, this plugin only support pandoc's span syntax...

**Comment by nonchip** [comment]
well it doesn't seem to do even that though, if you read the 2nd part of my message there with the error. or am i doing something wrong?

**Comment by mb21** [comment]
I'm using this package as part of https://panwriter.com and if I input your markdown source there, then it works as expected... 

maybe you're loading the dependencies in the wrong order..?

**Comment by nonchip** [comment]
your code is the very first bit i `use()`, then i have footnotes (unrelated), then attrs, then a bunch of other stuff (none of which uses any syntax that could interfere). i also tried loading attrs before yours, didn't help either. maybe you've got an older version of markdown-it-attrs and they changed something? i'm on 2.4.1

**Comment by mb21** [comment]
Nope, cannot reproduce.  Put the following in a file and call `node index.js`:

```
var md = require('markdown-it')()
            .use( require('markdown-it-bracketed-spans') )
            .use( require('markdown-it-attrs') )
console.log( md.render('GMs: [if you want to allow your group to start with a ship, the sum of all bonuses and health values should be `10 + 2*(number of characters)`]{.spoiler}') );
```

As does this (with all the required dependencies installed):

    var md = require('markdown-it-pandoc')()
    console.log( md.render('GMs: [if you want to allow your group to start with a ship, the sum of all bonuses and health values should be `10 + 2*(number of characters)`]{.spoiler}') );

**Comment by nonchip** [comment]
why did you close it though if you're asking for more info?

```
$ cat mdi.js ; echo "###"; node mdi.js
var md = require('markdown-it')()
            .use( require('markdown-it-bracketed-spans') )
            .use( require('markdown-it-attrs') )
console.log( md.render('GMs: [if you want to allow your group to start with a ship, the sum of all bonuses and health values should be `10 + 2*(number of characters)`]{.spoiler}') );
###
/home/kyra/Documents/PnP/TheElpisSystem/node_modules/markdown-it-attrs/utils.js:123
      token.attrJoin('class', attrs[j][1]);
            ^

TypeError: Cannot read property 'attrJoin' of undefined
    at Object.exports.addAttrs (/home/kyra/Documents/PnP/TheElpisSystem/node_modules/markdown-it-attrs/utils.js:123:13)
    at Object.transform (/home/kyra/Documents/PnP/TheElpisSystem/node_modules/markdown-it-attrs/patterns.js:131:15)
    at Array.curlyAttrs (/home/kyra/Documents/PnP/TheElpisSystem/node_modules/markdown-it-attrs/index.js:30:19)
    at Core.process (/home/kyra/Documents/PnP/TheElpisSystem/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/home/kyra/Documents/PnP/TheElpisSystem/node_modules/markdown-it/lib/index.js:523:13)
    at MarkdownIt.render (/home/kyra/Documents/PnP/TheElpisSystem/node_modules/markdown-it/lib/index.js:543:36)
    at Object.<anonymous> (/home/kyra/Documents/PnP/TheElpisSystem/mdi.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
```

my versions:
```json
    "markdown-it": "^9.0.1",
    "markdown-it-attrs": "^2.4.1",
    "markdown-it-bracketed-spans": "^1.0.1"
```
in panwriter (at least according to https://github.com/mb21/panwriter/blob/master/package.json) you're using an older version of both `markdown-it` and `-attrs`, did you try to reproduce it with their current ones or in your local panwriter setup? note also if that's (=them breaking compatibility somehow in the current version) the reason, `markdown-it-pandoc` will also break, since that doesn't list any versions in its package.json or readme, thus people will be fetching the up to date versions.

**Comment by mb21** [comment]
I closed it because I really cannot reproduce, see the attached folder. There you can see I have:

```
  "dependencies": {
    "katex": "^0.10.2",
    "markdown-it": "^9.0.1",
    "markdown-it-attrs": "^3.0.0",
    "markdown-it-bracketed-spans": "^1.0.1",
    "markdown-it-container": "^2.0.0",
    "markdown-it-deflist": "^2.0.3",
    "markdown-it-footnote": "^3.0.2",
    "markdown-it-implicit-figures": "^0.9.0",
    "markdown-it-pandoc": "^0.5.0",
    "markdown-it-sub": "^1.0.0",
    "markdown-it-sup": "^1.0.0",
    "markdown-it-texmath": "^0.5.5"
  }
```

[test.zip](https://github.com/mb21/markdown-it-bracketed-spans/files/3450336/test.zip)

But if you can give me a reproducible example, happy to reopen...

**Comment by nonchip** [comment]
you actually just solved the issue for me with:
```
    "markdown-it-attrs": "^3.0.0",
```

turns out in `2.4.1` (which was up to date a few days ago) they had a regression, which is now fixed after i updated it. thanks :)
